### ISSUE TITLE
robust_scale  is use future prices ?

### ISSUE THREAD

**Issue by loki-zhou** [ClementPerroud/RL-Trading-Agent#1]
def add_features(df):
    df["feature_close"] = robust_scale(df["close"].pct_change())
    df["feature_open"] = robust_scale(df["open"]/df["close"])
    df["feature_high"] = robust_scale(df["high"]/df["close"])
    df["feature_low"] = robust_scale(df["low"]/df["close"])
    df["feature_volume"] = robust_scale(df["volume"] / df["volume"].rolling(7*24).max())
    df.dropna(inplace= True) # Clean your data !
    return df
I think robust_scale must use future info

**Comment by ClementPerroud** [comment]
Hi,
Yes indeed it does. In my personal work, I don't use it this way.
It just wanted to make "easier" for the tutorial.
But to be sure that the model does not cheat, I usually create a
RobustScaler object that is fitted only of training data or a part of it.
And it is then used to scale validation, test, and live (if in production)
data.

**Comment by loki-zhou** [comment]
Thanks for your reply， good job
